- .github/workflows/CI.yml
- src/cli.rs
- src/zig.rs
https://github.com/rust-lang/rust/blob/582b6964a8868c9714881d9821d08415a8f4f13b/compiler/rustc_target/src/spec/windows_gnu_base.rs
> Add support for Windows gnu targets

- src/zig.rs
https://github.com/ziglang/zig/pull/10314
> Add `-undefined dynamic_lookup` support for macOS

- .github/workflows/CI.yml
- src/zig.rs
Implements https://github.com/messense/cargo-zigbuild/issues/18#issuecomment-1076339342
> Add macOS `SDKROOT` support

- src/zig.rs
Fixes #23 
I've verified that this fixes that problem, and I can build functions on Windows now 🎉 
> Fix zig command execution

- .github/workflows/CI.yml
- src/build.rs
- src/zig.rs
- tests/hello-rustls/Cargo.lock
- tests/hello-rustls/Cargo.toml
- tests/hello-rustls/src/main.rs
> Pass macOS `SDKROOT` as plain include/library/framework path

- .github/workflows/CI.yml
- src/build.rs
https://github.com/cargo-lambda/cargo-lambda/pull/79#issuecomment-1110474472
> Enable zig linker for native target

- src/zig.rs
> Switch from bash to sh for zig wrapper script

- .github/workflows/CI.yml
- Cargo.lock
- Cargo.toml
- src/bin/cargo-zigbuild.rs
- src/zig.rs
For https://github.com/PyO3/setuptools-rust/pull/267#issuecomment-1191968872
> Add `cargo-zigbuild metadata` subcommand

- src/zig.rs
> Add wrappers for `zig ar` and `zig ranlib`

- .github/workflows/CI.yml
- Cargo.lock
- Cargo.toml
- src/bin/cargo-zigbuild.rs
- src/zig.rs
- tests/hello-rustls/Cargo.lock
- tests/hello-rustls/Cargo.toml
- tests/hello-rustls/src/main.rs
- tests/hello-tls/Cargo.lock
Try to reproduce https://github.com/messense/cargo-zigbuild/issues/52#issuecomment-1207139993
> Fix `zig ar` command line too long issue on Windows

- .github/workflows/CI.yml
- src/zig.rs
> Use hardlink instead of symlink on Windows

- .github/workflows/CI.yml
- src/zig.rs
> Fix build for i686-pc-windows-gnu

- Dockerfile
We ran into an issue building related to ziglang/zig#12046, upgrading the zig version seems to fix this
> upgrade zig and rust in container

- src/zig.rs
Ref https://github.com/PyO3/maturin/issues/1369
> Remove broken symlink before creating new one

- src/zig.rs
Remove result from signature because this function always returns Ok.
> Allow to set a specific cache directory

- Cargo.lock
- Cargo.toml
- src/bin/cargo-zigbuild.rs
- src/build.rs
- src/check.rs
- src/clippy.rs
- src/install.rs
- src/lib.rs
- src/run.rs
- src/rustc.rs
- src/test.rs
- src/zig.rs
> Add `cargo-zigbuild install` subcommand

- .github/workflows/CI.yml
- src/zig.rs
> Expand bindgen test to include Windows

- .github/workflows/CI.yml
- src/zig.rs
> Try add more options to fix bindgen on macOS

- .github/workflows/CI.yml
- src/zig.rs
> Fallback to zig darwin libc when `SDKROOT` isn't set

- .github/workflows/CI.yml
> use the official sccache-action repo

- src/zig.rs
- tests/hello-windows/Cargo.lock
- tests/hello-windows/Cargo.toml
- tests/hello-windows/build.rs
> Add workaround for `-lsynchronization` linking issue for Windows GNU targets

- src/zig.rs
> Add basic support for WASM

- src/zig.rs
> typo zig: remove dash

- src/zig.rs
> fix zig: unsupported dylib

- src/zig.rs
> fix zig: unsupported list.def

- src/bin/cargo-zigbuild.rs
> Add support for external cargo subcommand

- Cargo.lock
- src/zig.rs
- tests/hello-rustls/Cargo.lock
> Remove `--target` argument from `cc-rs`

- src/zig.rs
When building a targeting a macos target you may get an error such as:
error: unsupported linker arg: -exported_symbols_list
A previous fix addressed the first variant of this flag where it is one argument. This fix addresses the second form of this flag where the symbols list is passed as a file path via a follow up argument.
Repros by building a cdylib targetting aarch64-apple-darwin.
Fixes #164
> fix: Handle -Wl,-exported_symbols_list <path>

- src/bin/cargo-zigbuild.rs
- src/zig.rs
> Use zig lib instead of zig ar for msvc targets

- src/zig.rs
https://github.com/ziglang/zig/wiki/FAQ#why-do-i-get-illegal-instruction-when-using-with-zig-cc-to-build-c-code
> Disable sanitizers
