- src/zig.rs
For some reason the linker strips away the debug information by default, making it impossible to debug or profile the produced executable file or to produce a meaningful backtrace on panic. This PR adds `-g` to the linker invocation parameter to prevent stripping.
<details>
<summary>Panic message comparison</summary>
Without `-g`:
```
thread 'main' panicked at 'User-requested panic', main.rs:11:5
stack backtrace:
0:       0x55574522e8 - <unknown>
1:       0x555746f7ec - <unknown>
2:       0x555744ef48 - <unknown>
3:       0x5557453b80 - <unknown>
4:       0x555745373c - <unknown>
5:       0x5557454340 - <unknown>
6:       0x5557453e0c - <unknown>
7:       0x55574527a0 - <unknown>
⋮ 
```
With `-g`:
```
thread 'main' panicked at 'User-requested panic', main.rs:11:5
stack backtrace:
0: …
```
> Pass `-g` to the linker to preserve debug info

- src/zig.rs
> Use /usr/bin/env to locate the bash interpreter

- .github/workflows/CI.yml
- Cargo.lock
- Cargo.toml
- src/build.rs
- src/zig.rs
> Enable unstable `target-applies-to-host` option automatically for nightly Rust

- .github/workflows/CI.yml
- Cargo.lock
- Cargo.toml
- src/build.rs
- src/rustc.rs
- src/zig.rs
First of all I want to say thank you for this incredible tool, it made our work so much easier.
As a part of our pipe line we need to build our program to multiple targets, recently a change has been made to the `cargo` cli allowing to pass a flag called `multitarget` which makes it possible to compile to multiple targets all at once.
The proposed changes follow the way the `cargo build` CLI works, see: 
https://github.dev/rust-lang/cargo/blob/06b9d31743210b788b130c8a484c2838afa6fc27/src/bin/cargo/commands/build.rs
```rs
fn arg_target_triple(self, target: &'static str) -> Self {
self._arg(multi_opt("target", "TRIPLE", target))
}
pub fn multi_opt(name: &'static str, value_name: &'static str, help: &'static str) -> Arg<'static> {
opt(name, help)
.value_name(value_name) …
```
> Supporting the nightly flag -Zmultitarget

- src/zig.rs
We need to execute the search command in a new Windows
shell to work, otherwise the command always fails with "Program not found".
> Fix Zig detection on Windows.

- src/zig.rs
This allows to customize where to find those tools.
It gives more flexibility in environments where there might be
more than one version of those tools and you want to use a specific one
without modifying the PATH.
> Allow to specify binary paths for python and zig.

- src/build.rs
> Fix `cannot allocate memory in static TLS block` on nightly Rust

- src/bin/cargo-zigbuild.rs
- src/lib.rs
- src/run.rs
- src/test.rs
Invoking as:
* `cargo-zigbuild run`
* `cargo-zigbuild test`
Closes #39
> Add `run` and `test` wrappers

- src/zig.rs
Instead of generating names like `zigcc-x86_64-unknown-linux-gnu..sh`, generates names like `zigcc-x86_64-unknown-linux-gnu.sh`.
> Remove double dot from linker wrapper.

- Dockerfile
I want to build target `x86_64-pc-windows-gnu`, but the Docker image doesn't have `x86_64-pc-windows-gnu`.
I add it to Dockerfile :)
> Add x86_64-pc-windows-gnu to Dockerfile

- src/bin/cargo-zigbuild.rs
- src/build.rs
- src/run.rs
- src/rustc.rs
- src/test.rs
- src/zig.rs
If `cargo-zigbuild` is used as library, `zig ar` is opt-in.
> Only enable `zig ar` in cargo-zigbuild binary by default

- .github/workflows/CI.yml
- src/zig.rs
https://github.com/ziglang/zig/commit/4848b28ec84edb719e780f164eac366ab2e83f22
> Add `-mcpu` option for arm* targets

- src/zig.rs
Although it does not compile as of zig v0.9.1: https://github.com/ziglang/zig/issues/3340
> Add `-mcpu` option for riscv64

- Cargo.lock
- Cargo.toml
- src/bin/cargo-zigbuild.rs
- src/check.rs
- src/clippy.rs
- src/lib.rs
Originally added basic clippy support. https://github.com/messense/cargo-zigbuild/pull/73/commits/e43e7afc4d564fa1e1d642139edeca630e0bcdff included `cargo-check` as a natural byproduct of supporting the full option set of `cargo-clippy`
See [messense/cargo-options#5](https://github.com/messense/cargo-options/pull/5) for discussion
> Add cargo-clippy, cargo-check support

- .github/workflows/CI.yml
- src/zig.rs
Closes #74
Can you direct me how to implement integration test, or could you do that?
> Bindgen support

- .github/workflows/Release.yml
- Cargo.lock
- src/zig.rs
> Filter out unsupported linker arg `--disable-auto-image-base` for Windows gnu targets

- .github/workflows/CI.yml
- src/zig.rs
> Fix build on zig 0.11 with Rust nightly

- .github/workflows/CI.yml
- src/zig.rs
> Use `x86-linux-*` for i585/i686 Rust targets on zig 0.11+

- src/zig.rs
Previously it fails to link with the following error:
```
ld.lld: error: relocation R_MIPS_32 cannot be used against local symbol; recompile with -fPIC
```
See https://github.com/ziglang/zig/issues/4925#issuecomment-1499823425
> Add a workaround for MIPS linking error

- src/zig.rs
Resolved in https://github.com/ziglang/zig/pull/15101
> Drop fcntl patch on zig 0.11+

- src/zig.rs
see https://github.com/rust-cross/cargo-zigbuild/issues/74#issuecomment-1507886083
basically, `BINDGEN_EXTRA_CLANG_ARGS_<target>` was always set (i.e. overwritten) even if the env variable was already set by the user. this target-specific env variable also precedes `BINDGEN_EXTRA_CLANG_ARGS` which becomes powerless. as a result, users were not able to pass their own arguments to clang for bindgen through env variables.
this fix checks if `BINDGEN_EXTRA_CLANG_ARGS` or `BINDGEN_EXTRA_CLANG_ARGS_<target>` was already set. if it was set by the user, cargo-zigbuild will not overwrite those values and leave them as is.
if both env vars are not set, cargo-zigbuild will keep its existing behavior by setting the clang sysroot.
> zig: do not overwrite bindgen env vars if already set

- src/zig.rs
`aarch64-unknown-linux-gnu` has the same problem, but I'm unable to workaround it like this (https://github.com/ziglang/zig/issues/14467).
```
Compiling sha2-asm v0.6.2
The following warnings were emitted during compilation:
warning: src/sha256_aarch64.S:75:2: error: instruction requires: sha2
warning:  sha256su0 v8.4s, v9.4s
warning:  ^
warning: src/sha256_aarch64.S:78:2: error: instruction requires: sha2
warning:  sha256h q2, q3, v6.4s
warning:  ^
warning: src/sha256_aarch64.S:79:2: error: instruction requires: sha2
warning:  sha256h2 q3, q4, v6.4s
warning:  ^
warning: src/sha256_aarch64.S:80:2: error: instruction requires: sha2
warning:  sha256su1 v8.4s, v10.4s, v11.4s
warning:  ^
warning: src/sha256_aarch64.S:83:2: error: instruction requires: sha2
warning:  sha256su0 v9.4s, v10.4s …
```
> Replace `armv8-a` with `apple_a14` for `aarch64-apple-darwin`

- src/zig.rs
https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html
> The `-isystem` and `-idirafter` options also mark the directory as a system directory, so that it gets the same special treatment that is applied to the standard system directories.
> Use `-isystem` instead of `-I` for macOS SDK header include

- src/zig.rs
- tests/hello-cmake/Cargo.lock
- tests/hello-cmake/Cargo.toml
- tests/hello-cmake/src/main.rs
> Fix build for aarch64 linux with `-march=armv8-a`

- src/macos/libcharset.1.tbd
- src/macos/mod.rs
- src/zig.rs
- tests/hello-rustls/Cargo.lock
```
= note: error: missing dynamic library dependency: '/usr/lib/libcharset.1.dylib'
note: tried /usr/lib/libcharset.1.tbd
note: tried /usr/lib/libcharset.1.dylib
```
> Add `libcharset.1.tbd` for Apple targets

- src/linux/mod.rs
- src/zig.rs
- Add rust version check since rust 1.72 fixes the weak symbol issues for musl
- Use a linker script to add missing symbols during linking for zig >= 0.11 and rust < 1.72 (it should be better than using `rust-lld` since we can use the old logic to adjust parameters passed to zig )
> A slightly better approach to add weak symbols to the build for musl 1.2.4

- src/zig.rs
> fix zig: unsupported exported_symbols_list

- src/zig.rs
A follow up to https://github.com/rust-cross/cargo-zigbuild/pull/184 because of Windows paths.
It might be safe to do `arg.ends_with(".def")`, which this PR can be switched to if that seems unlikely to break things.
> fix zig: unsupported list.def (part 2)

- README.md
I have summarized my findings and [linked to the issue that details them](https://github.com/rust-cross/cargo-zigbuild/issues/231#issuecomment-1983434802) for more information.
This helps communicate some surprises, both with dynamic and static linking support when considering `cargo zigbuild` as a solution. Some are UX issues with `cargo zigbuild` command, while others are upstream quirks with `zig cc`.
> docs: Add caveats for glibc version targeting feature

- src/bin/cargo-zigbuild.rs
- src/doc.rs
- src/lib.rs
Closes: https://github.com/rust-cross/cargo-zigbuild/issues/233
Note: this depends on https://github.com/messense/cargo-options/pull/10 being merged, released. Then Cargo.{toml,lock} here needs to be updated to use that version.  Testing was done locally using `[patch.crates-io]` and was successful.
> Add `cargo-zigbuild doc` support

- src/zig.rs
Fix https://github.com/rust-cross/cargo-zigbuild/issues/239
This PR simply adds a check for most wrapper writes: Try to read first, then write if the content should be changed.
Verified that ccache works across different builds for rust-rocksdb with the default config:
```
ccache --set-config=compiler_check=mtime # Default
```
```
[2024-04-16T13:44:19.059926 67945] Succeeded getting cached result
[2024-04-16T13:44:19.059943 67945] Result: direct_cache_hit
[2024-04-16T13:44:19.059944 67945] Result: local_storage_hit
[2024-04-16T13:44:19.059945 67945] Result: local_storage_read_hit
[2024-04-16T13:44:19.059946 67945] Result: local_storage_read_hit
```
> feat: Avoid touching wrapper files when content is unchanged

- src/zig.rs
> Quote executable path on Windows

- src/zig.rs
Early this year, WASI 0.2 has been stabilized, hence the need to differentiate wasi targets (https://blog.rust-lang.org/2024/04/09/updates-to-rusts-wasi-targets.html)
However, in Zig land Andrew decided to call this target `wasm32-wasi.0.1.0` (https://github.com/ziglang/zig/issues/19581#issuecomment-2057966056)
This PR makes '--target=wasm32-wasip1` work and removes the warnings when running `--target=wasm32-wasi`
I tried it out with (https://github.com/scristobal/cross-compiling-rust-c-wasm-zig) and it works just fine.
> Use new target wasm32-wasip1 that replaces wasm32-wasm

- .github/workflows/Release.yml
- Dockerfile.windows
- README.md
- Resolves #287
@messense I've created and tested this Dockerfile locally. ~However, I'm not familiar with uploading the image to ghcr.io/DockerHub. Please update the Release workflow accordingly.~ Thank you 😃 
Edit: The PR is now ready-to-merge. I've updated the Release workflow.
> Add windows docker image

- src/zig.rs
What this does: adds `CARGOZIGBUILD_RUSTC_VERSION` (idk what else to name it) variable that is used by `Zig::execute_compiler` to avoid calling `sccache rustc -vV` in some cases
> env hack to deal with sccache issues

- src/zig.rs
https://github.com/rust-cross/cargo-zigbuild/commit/02165f1e5be3a3354ef9f819182cbcce9c2412e1#diff-49b1f98d9d763bc0e0db9c28ba3dc79ca7413959f017924bc333f7a086d16189R520
post-rename, variables had `_` in different places
> fix _ typo in `CARGO_ZIGBUILD_RUSTC_VERSION`

- src/zig.rs
This makes `cargo zigbuild` work on nightly on Linux. Soon-ish this flag will be probably passed on x64 even on stable, which would render `cargo zigbuild` essentially unusable on Linux without support for ignoring the flag.
Fixes: https://github.com/rust-cross/cargo-zigbuild/issues/327
> Ignore `-znostart-stop-gc` linker flag

- README.md
Could perhaps do with some revision, but adding this information to the README may help raise some awareness about `cargo build` vs `cargo zigbuild` troubleshooting when `cargo zigbuild` fails to find headers/libs from standard system paths.
Perhaps there is a way to add `-isystem /usr/include` via `RUSTFLAGS` instead of `CFLAGS`, but I think it may be useful as-is since sometimes troubleshooting can involve building a C/C++ dep directly with Zig to compare why something differs with `cargo zigbuild`.
> chore: Add tips for troubleshooting glibc version support

- src/zig.rs
cmake fails with:
`error: unsupported linker arg: --dependency-file=...`
`--dependency-file` is currently not supported in zig.
https://github.com/ziglang/zig/issues/22213
This PR disables depfile support in cmake
> (fix) Disable depfile support

- src/zig.rs
When multiple processes try to build with Cargo-ZigBuild in parallel, the processes compete writing and removing these files, which can cause the builds to fail.
Since these empty files don't seem problematic, the most simple solution is to keep the files in the cache and reuse them for all invocations. That removes the race condition when two builders try to use them in parallel.
An alternative solution would be to create unique names for those files for every invocation. I don't think the added complexity is necessary, but I'd be happy to change the implementation.
@messense can you take a look at this and release a patch version if it works for you? This fixes this issue: https://github.com/cargo-lambda/cargo-lambda/issues/865
> Don't remove temporary empty files from the cache.
